# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Location Paths
source:                   ./
destination:              ./site

# Site Settings
locale:                   "en"
title:                    "FVCproductions"
title_separator:          "-"
name:                     "Frances Coronel"
name_type:                "Person"
description:              "I like to dabble with things that ought to be dabbled with. &#127827; &#127851;"
url:                      "https://fvcproductions.com"
baseurl:                  ""
repository:               "fvcproductions/fvcproductions.github.io"
teaser:                   "/assets/img/teaser.png"
og_image:                 "/assets/img/teaser.png"
words_per_minute:         200
github:                   [metadata] # removing GitHub Metadata Error
google_site_verification: biBOb6vq_csqy61DeBLw8DvAbCDUp5UsG8Vnpgm8qu4
bing_site_verification:   9C3D9366DA5BF33A14ABDFAF0A81CED3
comments:
  provider:               "disqus"
  disqus:
    shortname:            "fvcproductions"
atom_feed:
  path:                   # feed.xml

# Google - Structured Data
social:
  type:                   "Organization"
  name:                   "FVCproductions"
  links:
    - "https://twitter.com/fvcproductions"
    - "https://www.linkedin.com/in/fvcproductions"
    - "https://behance.net/fvcproductions"
    - "https://youtube.com/+fvcproductions2013"
    - "https://github.com/fvcproductions"
    - "https://speakerdeck.com/fvcproductions"

# Analytics
analytics:
  provider:               "google"
  google:
    tracking_id:          UA-63190978-3
    super_proxy_url:      "https://fvcproductions-analytics.appspot.com/query?id=ahpzfmZ2Y3Byb2R1Y3Rpb25zLWFuYWx5dGljc3IVCxIIQXBpUXVlcnkYgICAgICAgAoM&format=json"

# Site Author
author:
  name:                   "Frances Coronel"
  avatar:                 "assets/img/logo.png"
  bio:                    "I like to dabble with things that ought to be dabbled with."
  location:               "Redwood City, CA"
  email:                  "fvcproductions at gmail dot com"
  uri:                    "https://fvcproductions.com"
  codepen:                "fvcproductions"
  dribbble:               "fvcproductions"
  github:                 "fvcproductions"
  google_plus:            "fvcproductions2013"
  linkedin:               "fvcproductions"
  soundcloud:             "fvcproductions"
  spotify:                "fvcproductions"
  stackoverflow:          "3000467/fvcproductions"
  steam:                  "fvcproductions"
  tumblr:                 "fvcproductions2013"
  twitter:                "fvcproductions"
  youtube:                "fvcproductions2013"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding:                 "utf-8"
markdown_ext:             "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:                 kramdown
highlighter:              rouge
lsi:                      false
excerpt_separator:        ""
incremental:              false

# Markdown Processing
kramdown:
  input:                  GFM
  hard_wrap:              false
  auto_ids:               true
  footnote_nr:            1
  entity_output:          as_char
  toc_levels:             1..6
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  enable_coderay:         false

# Sass/SCSS
sass:
  sass_dir:               _sass
  style:                  compressed

# Outputting
permalink:                /blog/:year/:month/:day/:title/
timezone:                 America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type:                   liquid
  path:                   /categories/
tag_archive:
  type:                   liquid
  path:                   /tags/

# HTML Compression https: //jch.penibelst.de/
compress_html:
  clippings:              all
  comments:               all
  endings:                all
  ignore:
    envs:                 [local]
  blanklines:             false
  profile:                false
  startings:              all

# Defaults
defaults:
  # _posts
  - scope:
      path:               ""
      type:               posts
    values:
      layout:             single
      read_time:          true
      comments:           true
      share:              true
      related:            true
  # _pages
  - scope:
      path:               ""
      type:               pages
    values:
      layout:             single
  # _adventures
  - scope:
      path:               ""
      type:               adventures
    values:
      layout:             single
      read_time:          false
      comments:           true
      share:              true
      related:            true
  # _reviews
  - scope:
      path:               ""
      type:               reviews
    values:
      layout:             single
      read_time:          false
      comments:           true
      share:              true
      related:            true
  # _services
  - scope:
      path:               ""
      type:               services
    values:
      layout:             single
      read_time:          false
      comments:           false
      share:              true
      related:            true
    # _portfolio
  - scope:
      path:               ""
      type:               portfolio
    values:
      layout:             single
      read_time:          false
      comments:           true
      share:              true
      related:            true
  # _speaking
  - scope:
      path:               ""
      type:               speaking
    values:
      layout:             single
      read_time:          false
      comments:           true
      share:              true
      related:            true
  # _conferences
  - scope:
      path:               ""
      type:               conferences
    values:
      layout:             single
      read_time:          false
      comments:           true
      share:              true
      related:            true
    # _hackathons
  - scope:
      path:               ""
      type:               hackathons
    values:
      layout:             single
      read_time:          false
      comments:           true
      share:              true
      related:            true
  # _experience
  - scope:
      path:               ""
      type:               experience
    values:
      layout:             single
      read_time:          false
      comments:           true
      share:              true
      related:            true
  # _education
  - scope:
      path:               ""
      type:               education
    values:
      layout:             single
      read_time:          false
      comments:           true
      share:              true
      related:            true
    # _programs
  - scope:
      path:               ""
      type:               programs
    values:
      layout:             single
      read_time:          false
      comments:           true
      share:              true
      related:            true
  # _volunteering
  - scope:
      path:               ""
      type:               volunteering
    values:
      layout:             single
      read_time:          false
      comments:           true
      share:              true
      related:            true

# collections
collections:
  portfolio:
    output:               true
    permalink:            /portfolio/:year/:month/:day/:title/
  services:
    output:               true
    permalink:            /services/:year/:month/:day/:title/
  speaking:
    output:               true
    permalink:            /speaking/:year/:month/:day/:title/
  reviews:
    output:               true
    permalink:            /reviews/:year/:month/:day/:title/
  adventures:
    output:               true
    permalink:            /adventures/:year/:month/:day/:title/
  conferences:
    output:               true
    permalink:            /conferences/:year/:month/:day/:title/
  hackathons:
    output:               true
    permalink:            /hackathons/:year/:month/:day/:title/
  programs:
    output:               true
    permalink:            /programs/:year/:month/:day/:title/
  volunteering:
    output:               true
    permalink:            /volunteering/:year/:month/:day/:title/
  experience:
    output:               true
    permalink:            /experience/:year/:month/:day/:title/
  education:
    output:               true
    permalink:            /education/:year/:month/:day/:title/